-- =================================================================
-- Unified Business Management System (BMS) - Supabase Schema (FIXED)
-- Version: 2.1
-- Author: Gemini Systems Architect
-- Changes: Added organization_id to ALL tables for strictly enforcing Tenant Isolation.
-- =================================================================

BEGIN;

-- 1. Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================
-- Custom Types (Enums)
-- =============================================

DO $$ BEGIN
    CREATE TYPE public.app_role AS ENUM ('admin', 'architect', 'factory_mgr', 'sales');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.location_type AS ENUM ('showroom', 'factory', 'warehouse', 'office');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.project_status AS ENUM ('planning', 'concept', 'design_development', 'in_production', 'execution', 'completed', 'on_hold', 'cancelled');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.job_status AS ENUM ('pending', 'in_progress', 'cutting', 'stitching', 'polishing', 'quality_check', 'completed', 'blocked');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.order_status AS ENUM ('draft', 'confirmed', 'in_production', 'partially_shipped', 'shipped', 'delivered', 'cancelled');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.payment_status AS ENUM ('pending', 'paid', 'failed', 'refunded');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.commentable_type AS ENUM ('project', 'project_milestone', 'drawing', 'site_log', 'job_card', 'sales_order');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.sync_destination AS ENUM ('wordpress', 'pos');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.sync_status AS ENUM ('pending', 'success', 'failed');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- =============================================
-- Core Tables
-- =============================================

CREATE TABLE IF NOT EXISTS public.organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    address TEXT,
    type public.location_type NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    organization_id BIGINT REFERENCES public.organizations(id) ON DELETE SET NULL,
    first_name TEXT,
    last_name TEXT,
    role public.app_role NOT NULL DEFAULT 'sales',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- Products & Inventory
-- =============================================

CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    sku TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    wp_product_id BIGINT,
    pos_product_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(sku, organization_id)
);

CREATE TABLE IF NOT EXISTS public.raw_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    unit_of_measure TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- FIXED: Added organization_id and explicit Primary Key
CREATE TABLE IF NOT EXISTS public.bill_of_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    raw_material_id BIGINT NOT NULL REFERENCES public.raw_materials(id) ON DELETE CASCADE,
    quantity_required NUMERIC(10, 4) NOT NULL,
    UNIQUE(product_id, raw_material_id)
);

CREATE TABLE IF NOT EXISTS public.inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE, -- Ensure Tenant Isolation
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    raw_material_id BIGINT REFERENCES public.raw_materials(id) ON DELETE CASCADE,
    location_id BIGINT NOT NULL REFERENCES public.locations(id) ON DELETE CASCADE,
    quantity NUMERIC(10, 2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT inventory_item_check CHECK (
        (product_id IS NOT NULL AND raw_material_id IS NULL) OR
        (product_id IS NULL AND raw_material_id IS NOT NULL)
    ),
    UNIQUE(product_id, location_id),
    UNIQUE(raw_material_id, location_id)
);

-- =============================================
-- Architecture
-- =============================================

CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    client_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    status public.project_status NOT NULL DEFAULT 'planning',
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- FIXED: Added organization_id
CREATE TABLE IF NOT EXISTS public.project_milestones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    status public.project_status NOT NULL DEFAULT 'planning',
    due_date DATE
);

-- FIXED: Added organization_id
CREATE TABLE IF NOT EXISTS public.drawings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    project_milestone_id BIGINT NOT NULL REFERENCES public.project_milestones(id) ON DELETE CASCADE,
    uploader_id UUID NOT NULL REFERENCES public.profiles(id),
    storage_object_id UUID NOT NULL,
    version INT NOT NULL DEFAULT 1,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (project_milestone_id, storage_object_id, version)
);

-- FIXED: Added organization_id
CREATE TABLE IF NOT EXISTS public.site_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    author_id UUID NOT NULL REFERENCES public.profiles(id),
    log_date DATE NOT NULL DEFAULT CURRENT_DATE,
    notes TEXT,
    photos JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- Manufacturing (ERP)
-- =============================================

CREATE TABLE IF NOT EXISTS public.job_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    quantity_to_produce INT NOT NULL,
    status public.job_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    due_date DATE
);

-- FIXED: Added organization_id
CREATE TABLE IF NOT EXISTS public.job_card_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    job_card_id BIGINT NOT NULL REFERENCES public.job_cards(id) ON DELETE CASCADE,
    stage public.job_status NOT NULL,
    assignee_id UUID REFERENCES public.profiles(id),
    start_time TIMESTAMPTZ,
    end_time TIMESTAMPTZ,
    notes TEXT
);

-- FIXED: Added organization_id
CREATE TABLE IF NOT EXISTS public.material_consumption_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    job_card_id BIGINT NOT NULL REFERENCES public.job_cards(id) ON DELETE CASCADE,
    raw_material_id BIGINT NOT NULL REFERENCES public.raw_materials(id) ON DELETE CASCADE,
    quantity_consumed NUMERIC(10, 4) NOT NULL,
    quantity_wasted NUMERIC(10, 4) DEFAULT 0,
    logged_by UUID NOT NULL REFERENCES public.profiles(id),
    log_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- Sales & Payments
-- =============================================

CREATE TABLE IF NOT EXISTS public.sales_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    client_id UUID NOT NULL REFERENCES public.profiles(id),
    status public.order_status NOT NULL DEFAULT 'draft',
    total_amount NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- FIXED: Added organization_id
CREATE TABLE IF NOT EXISTS public.sales_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    sales_order_id BIGINT NOT NULL REFERENCES public.sales_orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id),
    quantity INT NOT NULL,
    price_per_unit NUMERIC(10, 2) NOT NULL
);

-- FIXED: Added organization_id
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    sales_order_id BIGINT NOT NULL REFERENCES public.sales_orders(id) ON DELETE CASCADE,
    amount NUMERIC(10, 2) NOT NULL,
    payment_method TEXT,
    status public.payment_status NOT NULL DEFAULT 'pending',
    transaction_id TEXT,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- Collaboration
-- =============================================

-- FIXED: Added organization_id
CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    author_id UUID NOT NULL REFERENCES public.profiles(id),
    content TEXT NOT NULL,
    target_type public.commentable_type NOT NULL,
    target_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_comments_polymorphic ON public.comments (target_type, target_id);

-- FIXED: Added organization_id
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    recipient_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    actor_id UUID REFERENCES public.profiles(id),
    action TEXT NOT NULL,
    target_comment_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE,
    target_project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- FIXED: Added organization_id
CREATE TABLE IF NOT EXISTS public.sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    target_id BIGINT NOT NULL,
    target_type TEXT NOT NULL,
    destination public.sync_destination NOT NULL,
    status public.sync_status NOT NULL DEFAULT 'pending',
    payload JSONB,
    response JSONB,
    initiated_at TIMESTAMTz NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);

-- =============================================
-- Functions & Triggers
-- =============================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id)
  VALUES (NEW.id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Safe trigger creation
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

CREATE OR REPLACE FUNCTION public.get_my_organization_id()
RETURNS BIGINT AS $$
BEGIN
  RETURN (SELECT organization_id FROM public.profiles WHERE id = auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================
-- RLS Policies (The Part That Was Broken)
-- =============================================

-- Now that ALL tables have organization_id, this loop works perfectly.
DO $$
DECLARE
    t_name TEXT;
BEGIN
    FOR t_name IN
        SELECT table_name FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_type = 'BASE TABLE'
          AND table_name NOT IN ('profiles', 'organizations') -- Skip specific custom logic tables
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t_name);

        -- Read
        EXECUTE format('
            DROP POLICY IF EXISTS "Allow org members to read" ON public.%I;
            CREATE POLICY "Allow org members to read" ON public.%I
            FOR SELECT USING (organization_id = public.get_my_organization_id());
        ', t_name, t_name);

        -- Insert
        EXECUTE format('
            DROP POLICY IF EXISTS "Allow org members to insert" ON public.%I;
            CREATE POLICY "Allow org members to insert" ON public.%I
            FOR INSERT WITH CHECK (organization_id = public.get_my_organization_id());
        ', t_name, t_name);

        -- Update
        EXECUTE format('
            DROP POLICY IF EXISTS "Allow org members to update" ON public.%I;
            CREATE POLICY "Allow org members to update" ON public.%I
            FOR UPDATE USING (organization_id = public.get_my_organization_id());
        ', t_name, t_name);
        
        -- Delete (Admin Only)
        EXECUTE format('
            DROP POLICY IF EXISTS "Allow admins to delete" ON public.%I;
            CREATE POLICY "Allow admins to delete" ON public.%I
            FOR DELETE USING (
                organization_id = public.get_my_organization_id() AND
                (SELECT role FROM public.profiles WHERE id = auth.uid()) = ''admin''::public.app_role
            );
        ', t_name, t_name);
    END LOOP;
END;
$$;

-- Manual Policies for Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow users to view all profiles in their org" ON public.profiles;
CREATE POLICY "Allow users to view all profiles in their org" ON public.profiles FOR SELECT
    USING (organization_id = public.get_my_organization_id());
    
DROP POLICY IF EXISTS "Allow users to update their own profile" ON public.profiles;
CREATE POLICY "Allow users to update their own profile" ON public.profiles FOR UPDATE
    USING (id = auth.uid());

-- Manual Policies for Organizations
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow members to view their own organization" ON public.organizations;
CREATE POLICY "Allow members to view their own organization" ON public.organizations FOR SELECT
    USING (id = public.get_my_organization_id());

-- =============================================
-- Kanban & Markup Extensions (v2.2)
-- =============================================

DO $$ BEGIN
    CREATE TYPE public.kanban_card_status AS ENUM ('backlog', 'todo', 'in_progress', 'in_review', 'done');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Rename drawings to drawing_revisions for clarity
ALTER TABLE IF EXISTS public.drawings RENAME TO drawing_revisions;

CREATE TABLE IF NOT EXISTS public.kanban_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    milestone_id BIGINT REFERENCES public.project_milestones(id) ON DELETE SET NULL,
    author_id UUID NOT NULL REFERENCES public.profiles(id),
    assignee_id UUID REFERENCES public.profiles(id),
    title TEXT NOT NULL,
    description TEXT,
    status public.kanban_card_status NOT NULL DEFAULT 'todo',
    due_date DATE,
    display_order REAL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.drawing_markups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    drawing_revision_id BIGINT NOT NULL REFERENCES public.drawing_revisions(id) ON DELETE CASCADE,
    author_id UUID NOT NULL REFERENCES public.profiles(id),
    markup_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Apply RLS policies to new tables
ALTER TABLE public.kanban_cards ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow org members to read" ON public.kanban_cards;
CREATE POLICY "Allow org members to read" ON public.kanban_cards FOR SELECT USING (organization_id = public.get_my_organization_id());
DROP POLICY IF EXISTS "Allow org members to insert" ON public.kanban_cards;
CREATE POLICY "Allow org members to insert" ON public.kanban_cards FOR INSERT WITH CHECK (organization_id = public.get_my_organization_id());
DROP POLICY IF EXISTS "Allow org members to update" ON public.kanban_cards;
CREATE POLICY "Allow org members to update" ON public.kanban_cards FOR UPDATE USING (organization_id = public.get_my_organization_id());
DROP POLICY IF EXISTS "Allow admins to delete" ON public.kanban_cards;
CREATE POLICY "Allow admins to delete" ON public.kanban_cards FOR DELETE USING (organization_id = public.get_my_organization_id() AND (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'::public.app_role);

ALTER TABLE public.drawing_markups ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow org members to read" ON public.drawing_markups;
CREATE POLICY "Allow org members to read" ON public.drawing_markups FOR SELECT USING (organization_id = public.get_my_organization_id());
DROP POLICY IF EXISTS "Allow org members to insert" ON public.drawing_markups;
CREATE POLICY "Allow org members to insert" ON public.drawing_markups FOR INSERT WITH CHECK (organization_id = public.get_my_organization_id());
DROP POLICY IF EXISTS "Allow org members to update" ON public.drawing_markups;
CREATE POLICY "Allow org members to update" ON public.drawing_markups FOR UPDATE USING (organization_id = public.get_my_organization_id());
DROP POLICY IF EXISTS "Allow admins to delete" ON public.drawing_markups;
CREATE POLICY "Allow admins to delete" ON public.drawing_markups FOR DELETE USING (organization_id = public.get_my_organization_id() AND (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'::public.app_role);


COMMIT;
