BEGIN;

-- Create a new status type specifically for milestones
DO $$ BEGIN
    CREATE TYPE public.milestone_status AS ENUM ('pending', 'in_progress', 'completed', 'on_hold');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Drop the old default and constraint, change the column type, set new default
ALTER TABLE public.project_milestones
    ALTER COLUMN status DROP DEFAULT,
    ALTER COLUMN status TYPE public.milestone_status USING status::text::public.milestone_status,
    ALTER COLUMN status SET DEFAULT 'pending';

-- Create invoice status enum
DO $$ BEGIN
    CREATE TYPE public.invoice_status AS ENUM ('draft', 'sent', 'paid', 'void');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create invoices table
CREATE TABLE IF NOT EXISTS public.invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    milestone_id BIGINT REFERENCES public.project_milestones(id) ON DELETE SET NULL,
    client_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    amount NUMERIC(10, 2) NOT NULL,
    status public.invoice_status NOT NULL DEFAULT 'draft',
    due_date DATE,
    pdf_storage_path TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Apply RLS
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow org members to read" ON public.invoices;
CREATE POLICY "Allow org members to read" ON public.invoices FOR SELECT USING (organization_id = public.get_my_organization_id());
DROP POLICY IF EXISTS "Allow org members to insert" ON public.invoices;
CREATE POLICY "Allow org members to insert" ON public.invoices FOR INSERT WITH CHECK (organization_id = public.get_my_organization_id());
DROP POLICY IF EXISTS "Allow org members to update" ON public.invoices;
CREATE POLICY "Allow org members to update" ON public.invoices FOR UPDATE USING (organization_id = public.get_my_organization_id());
DROP POLICY IF EXISTS "Allow admins to delete" ON public.invoices;
CREATE POLICY "Allow admins to delete" ON public.invoices FOR DELETE USING (organization_id = public.get_my_organization_id() AND (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'::public.app_role);

COMMIT;
