BEGIN;

-- Create attendance table
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    check_in TIMESTAMPTZ,
    check_out TIMESTAMPTZ,
    total_hours NUMERIC(5, 2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Apply RLS to attendance
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to read attendance"
ON public.attendance FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow admins to manage attendance"
ON public.attendance FOR ALL
TO authenticated
USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'::public.app_role);

-- Ensure portal_access_key uses gen_random_uuid() for future projects if not already
ALTER TABLE public.projects 
ALTER COLUMN portal_access_key SET DEFAULT gen_random_uuid();

COMMIT;
