BEGIN;

-- Create a reusable currency type for data integrity
DO $$ BEGIN
    CREATE TYPE public.currency_type AS ENUM ('USD', 'INR');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Rule 1: Each project must have a base currency.
ALTER TABLE public.projects
ADD COLUMN IF NOT EXISTS currency public.currency_type NOT NULL DEFAULT 'USD';

-- Rule 2: All monetary values must be stored with their currency.
-- This ensures that a value of "100" is never ambiguous.
ALTER TABLE public.invoices
ADD COLUMN IF NOT EXISTS currency public.currency_type;

ALTER TABLE public.time_logs
ADD COLUMN IF NOT EXISTS currency public.currency_type;

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS hourly_rate_currency public.currency_type NOT NULL DEFAULT 'USD';

-- Rule 3: Exchange rates must be stored for conversions.
CREATE TABLE IF NOT EXISTS public.exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_currency public.currency_type NOT NULL,
    to_currency public.currency_type NOT NULL,
    rate NUMERIC(14, 6) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(from_currency, to_currency)
);

-- Pre-populate with placeholder rates. In production, this would be updated by a cron job.
INSERT INTO public.exchange_rates (from_currency, to_currency, rate) 
VALUES ('USD', 'INR', 83.50), ('INR', 'USD', 0.012)
ON CONFLICT (from_currency, to_currency) DO NOTHING;

COMMIT;
