BEGIN;

-- Add hourly rate to profiles
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS hourly_rate NUMERIC(10, 2) DEFAULT 100.00;

-- Create time_logs table
CREATE TABLE IF NOT EXISTS public.time_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    kanban_card_id BIGINT NOT NULL REFERENCES public.kanban_cards(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    start_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    end_time TIMESTAMPTZ,
    duration_minutes INT,
    cost NUMERIC(10, 2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Apply RLS
ALTER TABLE public.time_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow org members to read" ON public.time_logs;
CREATE POLICY "Allow org members to read" ON public.time_logs FOR SELECT USING (organization_id = public.get_my_organization_id());
DROP POLICY IF EXISTS "Allow org members to insert" ON public.time_logs;
CREATE POLICY "Allow org members to insert" ON public.time_logs FOR INSERT WITH CHECK (organization_id = public.get_my_organization_id());
DROP POLICY IF EXISTS "Allow org members to update" ON public.time_logs;
CREATE POLICY "Allow org members to update" ON public.time_logs FOR UPDATE USING (organization_id = public.get_my_organization_id());
DROP POLICY IF EXISTS "Allow admins to delete" ON public.time_logs;
CREATE POLICY "Allow admins to delete" ON public.time_logs FOR DELETE USING (organization_id = public.get_my_organization_id() AND (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'::public.app_role);


COMMIT;
